# Copied and modified from https://github.com/grafana/tempo/blob/main/example/docker-compose/alloy/docker-compose.yaml
networks:
  tempo:
  grafana:

services:
  # Generate fake traces...
  k6-tracing:
    image: ghcr.io/grafana/xk6-client-tracing:latest
    command:
      - run
      - /template.js
    volumes:
      - ./k6tracing.js:/template.js:ro
    restart: always
    depends_on:
      - otel-collector
      - tempo
    networks:
      tempo:

        # To eventually offload to Tempo...
  tempo:
    image: grafana/tempo:latest
    container_name: tempo
    command: ["-config.file=/etc/tempo.yaml"]
    volumes:
      - ./tempo/tempo.yaml:/etc/tempo.yaml
      - ../../tmp/tempo-data:/tmp/tempo
    ports:
      - "14268" # jaeger ingest
      - "3200:3200" # tempo
      - "4317" # otlp grpc
      - "4318" # otlp http
      - "9411" # zipkin
    networks:
      tempo:
      grafana:
