receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
exporters:
  logging:
  otlp:
    endpoint: "http://agent:4317"
    tls:
      insecure: true
  azuremonitor:

service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [otlp, azuremonitor]
  telemetry:
    logs:
      level: "debug"
